### ISSUE TITLE
Fix home command not working and resulting in an exception.

### ISSUE THREAD

**Issue by dmccoystephenson** [Dans-Plugins/Medieval-Factions#1375]
[05-03-2022 16:45:29] DanTheTechMan issued server command: /mf home
[05-03-2022 16:45:32] Exception in thread "Thread-29" java.lang.IllegalStateException: PlayerTeleportEvent may only be triggered synchronously.
[05-03-2022 16:45:32] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:616)
[05-03-2022 16:45:32] at org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1020)
[05-03-2022 16:45:32] at org.bukkit.craftbukkit.v1_18_R1.entity.CraftEntity.teleport(CraftEntity.java:556)
[05-03-2022 16:45:32] at Medieval-Factions-4.6.4-ALPHA.jar//dansplugins.factionsystem.utils.PlayerTeleporter.teleportPlayer(PlayerTeleporter.java:22)
[05-03-2022 16:45:32] at Medieval-Factions-4.6.4-ALPHA.jar//dansplugins.factionsystem.utils.extended.Scheduler$DelayedTeleportTask.teleportPlayer(Scheduler.java:146)
[05-03-2022 16:45:32] at Medieval-Factions-4.6.4-ALPHA.jar//dansplugins.factionsystem.utils.extended.Scheduler$DelayedTeleportTask.run(Scheduler.java:130)

**Comment by dmccoystephenson** [comment]
This may be useful:
https://stackoverflow.com/questions/66704945/illegalstateexception-timeskipevent-may-only-be-triggered-synchronously
