### ISSUE TITLE
Fix new world with the same name getting created after deleting a world.

### ISSUE THREAD

**Issue by IamJabbles** [Dans-Plugins/Medieval-Factions#1420]
## Describe the bug
(A clear and concise description of what the bug is.)
The bug causes a deleted world to return once deleted with faction land inside. The created world is default and causes a crash when attempting to remove with faction land inside.

## To Reproduce
(Steps to reproduce the behavior)
Have Multiverse or other world plugin. Load the world with a factions claimed land. Attempt to remove the world through Multiverse or deleting the world. Watch as the server suspends instead of crashes.. Attempt to reload the server and watch as a new world with the same name has been created.
## Expected behavior
(A clear and concise description of what you expected to happen.)
I expected the world to delete and not suspend. I expected the MF land to remove itself instead of removing the server.
## Screenshots or Logs
(If applicable, add screenshots to help explain your problem.)
- [Thu 16:19:03 ERROR com.destroystokyo.paper.io.PaperFileIOThread] Failed to read chunk data for task: Task for world: 'EyumelBeta' at 572,94 poi: false, hash: 269588013
java.nio.channels.ClosedChannelException
    at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:156)
    at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:790)
    at net.minecraft.world.level.chunk.storage.RegionFile.getChunkDataInputStream(RegionFile.java:604)
    at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:195)
    at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:187)
    at net.minecraft.world.level.chunk.storage.ChunkStorage.read(ChunkStorage.java:147)
    at net.minecraft.server.level.ChunkMap.f(ChunkMap.java:1700)
    at net.minecraft.server.level.ServerLevel$2.readData(ServerLevel.java:362)
    at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:508)
    at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118)
    at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51)
## Java version
 - [ ] Java 8
 - [ ] Java 11
 - [ ] Java 16
 - [ X] Java 17 

**Plugin version**
 - [ ] v4.1
 - [ ] v4.2
 - [ ] v4.3
 - [ ] v4.4
 - [ ] v4.5.x
 - [ X] v4.6.4.2
---
**Spigot/Paper version** _(Please Specify which server software you are using)_
 - [ ] 1.16.x
 - [ ] 1.17.x
 - [ X] 1.18.x

**Comment by dmccoystephenson** [comment]
This is probably happening because we create a world when loading home locations. If we changed how we were handling that, this would probably be fixed.
