### ISSUE TITLE
Fix error: "this.coord1" is null

### ISSUE THREAD

**Issue by ConfusedAlex** [Dans-Plugins/Medieval-Factions#1501]
## Describe the bug
Plugin cannot invoke dansplugins.factionsystem.objects.helper.GateCoord.getWorld() because this.coord1 is null

## To Reproduce
I dont know what to do to reproduce. This error gets from constantly.

## Expected behavior
No error

## Screenshots or Logs
```[06:00:59] [Server thread/WARN]: [MedievalFactions] Task #40 for MedievalFactions v4.7.0-SNAPSHOT generated an exception
java.lang.NullPointerException: Cannot invoke "dansplugins.factionsystem.objects.helper.GateCoord.getWorld()" because "this.coord1" is null
	at dansplugins.factionsystem.objects.domain.Gate.save(Gate.java:98) ~[Medieval-Factions-4.7.0-SNAPSHOT.jar:?]
	at dansplugins.factionsystem.objects.domain.Faction.save(Faction.java:410) ~[Medieval-Factions-4.7.0-SNAPSHOT.jar:?]
	at dansplugins.factionsystem.data.PersistentData$LocalStorageService.saveFactions(PersistentData.java:1351) ~[Medieval-Factions-4.7.0-SNAPSHOT.jar:?]
	at dansplugins.factionsystem.data.PersistentData$LocalStorageService.save(PersistentData.java:1328) ~[Medieval-Factions-4.7.0-SNAPSHOT.jar:?]
	at dansplugins.factionsystem.utils.extended.Scheduler$1.run(Scheduler.java:50) ~[Medieval-Factions-4.7.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-123]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1492) ~[paper-1.19.2.jar:git-Paper-123]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-123]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1416) ~[paper-1.19.2.jar:git-Paper-123]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.2.jar:git-Paper-123]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-123]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

## Java version
 - [ ] Java 8
 - [ ] Java 11
 - [ ] Java 16
 - [x] Java 17 

**Plugin version**
 - [ ] v4.1
 - [ ] v4.2
 - [ ] v4.3
 - [ ] v4.4
 - [x] v4.5.x
---
**Paper version**
 - [ ] 1.16.x
 - [ ] 1.17.x
 - [ ] 1.18.x
 - [x] 1.19.2

**Comment by ConfusedAlex** [comment]
There was a gate in the factions.json that didnt exist in the game. Deleted the gate in the json, now everything is working again.
Should this be closed?

**Comment by dmccoystephenson** [comment]
I'm glad you found a solution :) It wouldn't hurt to throw a null check in there so that people don't experience the error in the console in the future, so we can leave this open.
