### ISSUE TITLE
Can't run the plugin [HikariPool]

### ISSUE THREAD

**Issue by kauf0** [Dans-Plugins/Medieval-Factions#1709]
## Describe the bug
Simply plugin does not start!

## To Reproduce
I didn't find any dependencies for this plugin so I just put it in the plugin folder and reloaded the server. 

## Expected behavior
Well, actually, I was expecting for it to work, ahah! But it just doesn't

## Screenshots or Logs
```
[13:55:25 INFO]: [MedievalFactions] Enabling MedievalFactions v5.1.3
[13:55:25 INFO]: [com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
**[13:55:27 ERROR]: [com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool] HikariPool-1 - Exception during pool initialization.** 
org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: "java.net.UnknownHostException: debian: debian: Name or service not known" [90028-200] 
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[medieval-factions-5.1.3-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[medieval-factions-5.1.3-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[medieval-factions-5.1.3-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[medieval-factions-5.1.3-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[medieval-factions-5.1.3-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.init(HikariPool.java:100) ~[medieval-factions-5.1.3-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.HikariDataSource.init(HikariDataSource.java:81) ~[medieval-factions-5.1.3-all.jar:?]
at com.dansplugins.factionsystem.MedievalFactions.onEnable(MedievalFactions.kt:162) ~[medieval-factions-5.1.3-all.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-448] 
```
(I guess, that's all)

**Spigot/Paper version**
 - [x] 1.19.3 - git-Paper-448

**Comment by alyphen** [comment]
Your database is misconfigured.
Are you using h2 or mysql?

**Comment by kauf0** [comment]
Hello, @alyphen 
It's me texted in discord with this problem and you helped me, so for now I close the issue as completed. Thanks again!
