### ISSUE TITLE
Plugin not loading (Name or service not known)

### ISSUE THREAD

**Issue by TangledWiresYT** [Dans-Plugins/Medieval-Factions#1786]
## Describe the bug
When starting the server, Medieval Factions throws an error.

## To Reproduce
Install the plugin and run the server

## Expected behavior
The plugin should load.

## Screenshots or Logs
(If applicable, add screenshots to help explain your problem.)
`[com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Starting...

Console
11:34:03

at com.dansplugins.factionsystem.shadow.org.h2.Driver.connect(Driver.java:59) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[medieval-factions-5.3.0-all.jar:?]
... 15 more
Caused by: java.net.UnknownHostException: marvin: Name or service not known
at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:52) ~[?:?]
at java.net.InetAddress$PlatformResolver.lookupByName(InetAddress.java:1048) ~[?:?]
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1648) ~[?:?]
at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:997) ~[?:?]
at java.net.InetAddress.getAllByName0(InetAddress.java:1638) ~[?:?]
at java.net.InetAddress.getLocalHost(InetAddress.java:1751) ~[?:?]
at com.dansplugins.factionsystem.shadow.org.h2.util.NetUtils.getLocalAddress(NetUtils.java:282) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.org.h2.server.TcpServer.getURL(TcpServer.java:195) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.org.h2.tools.Server.start(Server.java:522) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.org.h2.engine.Database.startServer(Database.java:672) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.org.h2.engine.Database.<init>(Database.java:317) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.org.h2.engine.Engine.openSession(Engine.java:92) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.org.h2.engine.Engine.openSession(Engine.java:222) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.org.h2.engine.Engine.createSession(Engine.java:201) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.org.h2.Driver.connect(Driver.java:59) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[medieval-factions-5.3.0-all.jar:?]
at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[medieval-factions-5.3.0-all.jar:?]`

## Java version
- Java 18

**Plugin version**
- 5.3.0
---
**Spigot/Paper version** _(Please Specify which server software you are using)_
- Paper 1.20.1

**Comment by TangledWiresYT** [comment]
Just needed to add the hostname to `/etc/hosts`. Now it works
