### ISSUE TITLE
Bug Report 

### ISSUE THREAD

**Issue by DehlosF** [Dans-Plugins/Medieval-Factions#1803]
My plugin don't work :c

## To Reproduce
When I try to use plugin commands, I get this.
com.dansplugins.factionsystem.shadow.org.h2.jdbc.JdbcSQLNonTransientException: (Message 90028 not found) [90028-214]
        at com.dansplugins.factionsystem.shadow.org.h2.message.DbException.getJdbcSQLException(DbException.java:554) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.message.DbException.get(DbException.java:212) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.message.DbException.convert(DbException.java:387) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.util.NetUtils.getLocalAddress(NetUtils.java:284) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.server.TcpServer.getURL(TcpServer.java:195) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.tools.Server.start(Server.java:522) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Database.startServer(Database.java:672) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Database.<init>(Database.java:317) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Engine.openSession(Engine.java:92) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Engine.openSession(Engine.java:222) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Engine.createSession(Engine.java:201) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.Driver.connect(Driver.java:59) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
        at com.dansplugins.factionsystem.MedievalFactions.onEnable(MedievalFactions.kt:156) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:546) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:460) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:588) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:413) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.net.UnknownHostException: 92ba4953-66e7-4958-9ac5-97ce4ce0b4dd: 92ba4953-66e7-4958-9ac5-97ce4ce0b4dd: Name or service not known
        at java.net.InetAddress.getLocalHost(InetAddress.java:1936) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.util.NetUtils.getLocalAddress(NetUtils.java:282) ~[?:?]
        ... 29 more
Caused by: java.net.UnknownHostException: 92ba4953-66e7-4958-9ac5-97ce4ce0b4dd: Name or service not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:52) ~[?:?]
        at java.net.InetAddress$PlatformResolver.lookupByName(InetAddress.java:1211) ~[?:?]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1828) ~[?:?]
        at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1139) ~[?:?]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1818) ~[?:?]
        at java.net.InetAddress.getLocalHost(InetAddress.java:1931) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.util.NetUtils.getLocalAddress(NetUtils.java:282) ~[?:?]
        ... 29 more
[17:36:51] [Server thread/ERROR]: Error occurred while enabling MedievalFactions v5.3.0 (Is it up to date?)
com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: (Message 90028 not found) [90028-214]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
        at com.dansplugins.factionsystem.MedievalFactions.onEnable(MedievalFactions.kt:156) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:546) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:460) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:588) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:413) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: com.dansplugins.factionsystem.shadow.org.h2.jdbc.JdbcSQLNonTransientException: (Message 90028 not found) [90028-214]
        at com.dansplugins.factionsystem.shadow.org.h2.message.DbException.getJdbcSQLException(DbException.java:554) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.message.DbException.get(DbException.java:212) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.message.DbException.convert(DbException.java:387) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.util.NetUtils.getLocalAddress(NetUtils.java:284) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.server.TcpServer.getURL(TcpServer.java:195) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.tools.Server.start(Server.java:522) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Database.startServer(Database.java:672) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Database.<init>(Database.java:317) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Engine.openSession(Engine.java:92) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Engine.openSession(Engine.java:222) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Engine.createSession(Engine.java:201) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.Driver.connect(Driver.java:59) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[?:?]
        at com.dansplugins.factionsystem.shadow.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[?:?]
        ... 14 more
Caused by: java.net.UnknownHostException: 92ba4953-66e7-4958-9ac5-97ce4ce0b4dd: 92ba4953-66e7-4958-9ac5-97ce4ce0b4dd: Name or service not known
        at java.net.InetAddress.getLocalHost(InetAddress.java:1936) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.util.NetUtils.getLocalAddress(NetUtils.java:282) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.server.TcpServer.getURL(TcpServer.java:195) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.tools.Server.start(Server.java:522) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Database.startServer(Database.java:672) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Database.<init>(Database.java:317) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Engine.openSession(Engine.java:92) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Engine.openSession(Engine.java:222) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.Engine.createSession(Engine.java:201) ~[?:?]
        at com.dansplugins.factionsystem.shadow.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338) ~[?:?]

## Expected behavior
Apologies
It's the first time I write here. When I install the plugin I get the above error

In the game I get the list of commands but none of them work

## Screenshots or Logs
In the game it looks like this
![cap](https://github.com/Dans-Plugins/Medieval-Factions/assets/173792679/8c481f5c-bc75-4248-a10b-ac0e3909bcf2)

## Java version
Java 21

**Plugin version**
5.3.0-ALL
---
**Spigot/Paper version** _(Please Specify which server software you are using)_
 Paper 1.20.1

**Comment by 7AXEL** [comment]
Check out this project: https://github.com/7AXEL/Web2APK

**Comment by dmccoystephenson** [comment]
Thanks for the additional details! The error points to a database connection issue, likely involving HikariCP. It seems the plugin is unable to initialize the connection pool, which might be due to misconfigured database credentials or an incompatible database version.  

Could you double-check your database settings in the config file? If everything looks correct, providing the full error log would help us pinpoint the issue further. Thanks for your patience, and we’ll work to resolve this!
